# Generated by Django 4.2.6 on 2024-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_datab_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='datab',
            name='jn',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='datab',
            name='my',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='datab',
            name='sn',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='datab',
            name='vn',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
