# Generated by Django 4.2.6 on 2024-09-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
